version: '3.0'

services:
  conveyor-node:
    build: api/
  conveyorized-kibana:
    build: 
      context: plugin/
      args:
        - ELASTIC_TAG=${ELASTIC_TAG:-6.2.3}
  channel-load:
    build: channel-sources
    volumes:
     - ${CHANNEL_FOLDER:-./channel-sources/}:/usr/src/app
