# Specify the ES Connection Information
elasticsearch:
  url: http://elasticsearch:9200
  auth-method: none

# Specify the Node-RED URL
node-red:
  url: http://localhost:1880

# Specify where we can reach the conveyor API internal to Node-RED
conveyor-api:
  url: http://localhost:4000

kibana:
  url: http://kibana:5601